### ISSUE TITLE
Question about volatile in Madgwic class.

### ISSUE THREAD

**Issue by CAHEK7** [amperka/Troyka-IMU#10]
Is there any strong reason to use volatile modifier for quaternions in Madgwic class?
Removing it makes code about 11% faster and about 7% smaller.

**Comment by CAHEK7** [comment]
Just some side note about volatile. It does make sense only if the memory access for that type is atomic.
For AVR controllers volatile is useless for any types larger than byte, because any updates of such types are split into multiple register-memory accesses and can't be atomic. You can easily get interrupt right in the middle of the reading or writing of `volatile float` variable and corrupt half of the variable.

**Comment by nomad605dis** [comment]
Fixed #19
