### ISSUE TITLE
Library properties and keywords for Arduino IDE

### ISSUE THREAD

**Issue by CAHEK7** [amperka/Troyka-IMU#12]
Have you considered to make library.properties\library.json\keyword.txt files to be more integrated with Arduino IDE?

**Comment by nomad605dis** [comment]
Hi!

Yes of course it would be great. But maybe later.

**Comment by Shatki** [comment]
Hi!
It seems to me in file Troyka-IMU/GOST_81.cpp at line 63:
`for (idx = 1; idx < GOST4401_LUT_RECORDS - 1; idx++) {`
necessary: 
`for (idx = 0; idx < GOST4401_LUT_RECORDS - 1; idx++) {`  
?
Please check it
This mistake in cycle leads to a wrong result of calculating atmospheric pressure on height down 20000 meters.
