### ISSUE TITLE
GOST4401_81.cpp possible has a mistake

### ISSUE THREAD

**Issue by Shatki** [amperka/Troyka-IMU#13]
Hi!
It seems to me in file Troyka-IMU/GOST4401_81.cpp at line 63:
`for (idx = 1; idx < GOST4401_LUT_RECORDS - 1; idx++) {`
necessary: 
`for (idx = 0; idx < GOST4401_LUT_RECORDS - 1; idx++) {`

?
This mistake in cycle leads to an incorrect result of calculating atmospheric pressure on height down 20000 meters.

The same mistake has in function `GOST4401_getTemperature`

Please check it

**Comment by postusername** [comment]
Mmmm, i think is none mistake here. That cycle chooses a value from the table, and the first is **calibration zero**
