### ISSUE TITLE
No need to wait after Wire.requestFrom() and it should not be followed by Wire.endTransmission().

### ISSUE THREAD

**Issue by Koepel** [amperka/Troyka-IMU#18]
In the file "LPS331.cpp", you may remove the waiting with a while-loop and the `Wire.endTransmission()` after a `Wire.requestFrom()`.
Explanation: [Common-mistakes](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes), number 1 and 2.

In the file "stmhw.cpp", you may remove the function "waitForData()" because there is no such thing as waiting after a `Wire.requestFrom()`.

**Comment by nomad605dis** [comment]
Fixes #19
