### ISSUE TITLE
LIS3MDL_TWI::_ctrlReg3 is uninitialized

### ISSUE THREAD

**Issue by CAHEK7** [amperka/Troyka-IMU#2]
`LIS3MDL_TWI::_ctrlReg3` is private, can't be set from the outside of the class and used in `LIS3MDL_TWI::writeCtrlReg3()` in `LIS3MDL_TWI::begin()` function. Most probably it is zeroed out by compiler but I guess it should be initialized explicitly in constructor or right before `LIS3MDL_TWI::writeCtrlReg3()` invocation.

**Comment by CAHEK7** [comment]
Seems similar problem exists in all other modules. `*::begin()` functions made assumptions that appropriate _ctrlReg are zero-initialized.

**Comment by nkrkv** [comment]
Thank you for the report.

@Igor89 Take a look, please.

**Comment by CAHEK7** [comment]
May I ask about any commit or comment? As I can see the problem is still exist...

**Comment by nomad605dis** [comment]
Hi!

_ctrlReg3 after your changes is protected in file stmhw.h
And can you give me your email.

**Comment by CAHEK7** [comment]
Sure, check my github profile.
_ctrlReg is protected, but it's still not initialized. I can fix it, if you have no objections.

**Comment by nomad605dis** [comment]
Yes of course.
We are just glad this change.
