### ISSUE TITLE
Inconsistency between single LIS3MDL_TWI::readCalibrateGaussX[YZ] methods and bulk LIS3MDL_TWI::readCalibrateGaussXYZ method.

### ISSUE THREAD

**Issue by CAHEK7** [amperka/Troyka-IMU#5]
It seems strange for me that each single `LIS3MDL_TWI::readCalibrateGaussX[YZ]` method  returns scaled value: `return readCalibrateX[YZ]()/_mult;`
But bulk method `LIS3MDL_TWI::readCalibrateGaussXYZ` returns raw values:
`*x = _xCalibrate;
*y = _yCalibrate;
*z = _zCalibrate;`
Is it by design or just a typo?

**Comment by nomad605dis** [comment]
Hi!
Yes that's right. Thank you very much for your attention.
We are all correct. And check your branch library updated.
Thanks again.
